version: '3.5'
services:
  minkenet:
    container_name: minkenet
    image: registry.minkebox.net/minkebox/minkenet
    volumes:
    - ${DB-db}:/app/db
    network_mode: "host"
    cap_add:
    - NET_ADMIN
    environment:
    - DEBUG=${DEBUG-}
    shm_size: 256M
volumes:
  db:
